<?php
/**
 * Created by PhpStorm.
 * User: keepwin100
 * Date: 2019-06-01
 * Time: 22:41
 */
namespace  app\test\controller;
use app\account\controller\User;
use authority\logic\RoleLogic;
use authority\logic\UserLogic;
use authority\service\UserService;
use core\controller\Base;
use core\controller\tool\ApiPagination;

class Authority extends Base
{
    use ApiPagination;
    /**
     * @var UserLogic
     */
    protected $userlogic;
    /**
     * @var RoleLogic
     */
    protected $role_logic;

    /**
     * @var UserService
     */
    protected $userService;

    public function _initialize()
    {
        $this->userlogic = UserLogic::singleton();

        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    public function User()
    {
        $option = $this->request->param("opt");
        if($option =="ts"){
            $this->userService = UserService::singleton();
            $flag= $this->userService->loginExists("yyadmin");
            $flag2= $this->userService->mobileExists('13016966878');
        }
        if($option =='getUsers'){
           $user = $this->userlogic->getUsersList($this->paginationParams());
           $this->result($user);
        }
        if($option =="addUser"){
            //$this->checkRequest();
            $user = $this->userlogic->addUserByData($this->request->param());
            $this->result($user);
        }
        if($option =="disable"){
            $user  = $this->userlogic->disAbleUserById($this->request->param("uid"));
        }
    }

    public function Role()
    {
        $this->role_logic = RoleLogic::singleton();
        $option = $this->request->param("opt");
        if ($option == "ts") {

        }
        if ($option == "addRole") {
            $name = $this->request->param("name");
            $description = $this->request->param("description");
            $res = $this->role_logic->addRole($name,$description);
            $this->result($res);
        }elseif($option =="edit")
        {
            $rid = $this->request->param("rid");
            $name = $this->request->param("name");
            $description = $this->request->param("description");
            $res = $this->role_logic->editRole($rid,$name,$description);
            $this->result($res);
        }

    }
}
