<?php
/**
 * 登录 验证登录控制器
 * User: keepwin100
 * Date: 2019-06-02
 * Time: 12:39
 */
namespace authority\controller;
use authority\logic\IdentifyLogic;
use core\controller\Base;

class AbsIdentify extends Base
{
    /**
     * @var IdentifyLogic
     */
    protected $identifyLogic;

    public function _initialize()
    {
        $this->identifyLogic = IdentifyLogic::singleton();
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function login()
    {
        $username = $this->request->param("username");
        $pwd = $this->request->param("password");
        $result = $this->identifyLogic->login($username,$pwd);
        $this->result($result,0,"登录成功");
    }

    public function logout()
    {
        $this->identifyLogic->logout();
        $this->result("",0,"退出成功");
    }

    public function mobileLogin()
    {
        $mobile = $this->request->param("mobile");
        $vcode = $this->request->param("vcode");
        $result = $this->identifyLogic->loginByMobile($mobile,$vcode);
        $this->result($result,0,"登录成功");
    }

    public function sendPassCode()
    {
        $mobile = $this->request->param("mobile");
        $result = $this->identifyLogic->sendPassCode($mobile);
        $this->result($result,0,"登录成功");
    }
}
