#!/usr/bin/env php
<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006-2016 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: yunwuxin <448901948@qq.com>
// +----------------------------------------------------------------------

// 定义项目路径

define('APP_PATH', __DIR__ . '/application/');
define('CONF_PATH', APP_PATH . '../config/');
define("BLW_LOG_PATH", __DIR__."/tmp/log/");
define("EXTEND_PATH", APP_PATH."../extend/");
// 加载框架引导文件
require __DIR__.'/thinkphp/console.php';
