<?php

return [

    ERROR_PREFIX . STATUS_CODE_COMMUNITY_NOT_FOUND => "指定社区不存在",
    ERROR_PREFIX . STATUS_CODE_COMMUNITY_AREADY_EXISTS => "同名社区已经存在",
    ERROR_PREFIX . STATUS_CODE_ON_COMMUNITY_ID => "指定社区ID不正确",
    ERROR_PREFIX . STATUS_CODE_BUILDING_NO_NAME => "需要指定名称",
    ERROR_PREFIX . STATUS_CODE_ADD_BUILDING_FAILED => "添加建筑失败",
    ERROR_PREFIX . STATUS_CODE_BUILDING_NAME_EXISTS => "建筑名称重复",
    ERROR_PREFIX . STATUS_CODE_EDIT_BUILDING_FAILED => "修改失败",
    ERROR_PREFIX . STATUS_CODE_EDIT_FAMILY_FAILED => "修改失败",
    ERROR_PREFIX . STATUS_CODE_ADD_FAMILY_FAILED => "添加失败",
    ERROR_PREFIX . STATUS_CODE_FAMILY_NO_EXISTS => "家不存在",
];
