<?php
namespace app\bladmin\controller;
use core\controller\Admin;
use core\controller\tool\ApiPagination;
use core\service\ServiceManagement;
/**
 * 用户管理
 * User: keepwin100
 * Date: 2018-12-05
 * Time: 14:38
 */
 class Member extends Admin
 {
     use ApiPagination;

     protected $memberService;

     public  function _initialize()
     {
         $this->memberService = ServiceManagement::singleton()->get("member");
         parent::_initialize(); // TODO: Change the autogenerated stub
     }

     /**
      * 获取用户列表
      */
     public function getMembers()
     {
         $members = $this->memberService->searchInstances($this->paginationParams());
         $this->result($members);
     }




 }
