<?php
/**
 * 角色管理
 * User: keepwin100
 * Date: 2019-06-11
 * Time: 09:58
 */

namespace app\bladmin\controller;

use app\bladmin\validate\RoleAdminValidate;
use authority\logic\RoleLogic;
use core\controller\Admin;
use core\controller\tool\ApiPagination;

class Role extends Admin
{
    use ApiPagination;

    /**
     * @var RoleLogic
     */
    protected $logic;

    protected $validate = RoleAdminValidate::class;

    public function _initialize()
    {
        $this->logic = RoleLogic::singleton();
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 获取角色列表
     */
    public function getRoles()
    {
        $result = $this->logic->getRolesByParams($this->paginationParams());
        $this->result($result);
    }

    /**
     * 获取角色权限列表
     */
    public function getRoleAuth()
    {

    }

    /**
     * 添加角色
     */
    public function addRole()
    {
        $this->checkRequest();
        $name = $this->request->param("add_name");
        $description = $this->request->param("add_description");
        $auth_ids = $this->request->param("auth_ids");
        $res = $this->logic->addRole($name,$description,$auth_ids);
        $this->result($res);
    }

    public function modifyRole()
    {

    }

    public function deleteRole()
    {

    }

    public function disableRole()
    {

    }
    public function enableRole()
    {

    }


}