<?php
// #----系统、参数状态-----start----##
//中间位00【系统相关】

return [
    ERROR_PREFIX . STATUS_API_EXCEPTION => "API异常",
    ERROR_PREFIX . STATUS_API_TOKEN_EXPIRE => "无效的token",
    ERROR_PREFIX . STATUS_API_TOKEN_TOO_CONTINUALLY => "token请求太频繁",
    ERROR_PREFIX . STATUS_API_TOKEN_MUST_NOT_NULL => "token不能为空",
    ERROR_PREFIX . STATUS_INVALID_APPID => "ACCESS_KEY无效",
    ERROR_PREFIX . STATUS_INVALID_SECRET => "SECRET无效",
    ERROR_PREFIX . STATUS_INVALID_TYPE => "请求类型无效",
    ERROR_PREFIX . STATUS_API_TOKEN_WILL_BE_EXPIRED => "token即将过期",
   
];