<?php
return [

    ERROR_PREFIX . STATUS_CODE_USER_FAILED => '用户错误',
    ERROR_PREFIX . STATUS_CODE_AUTH_FAILED => '用户鉴权失败',
    ERROR_PREFIX . STATUS_CODE_SESSION_TIMEOUT => '退出登录状态',

    ERROR_PREFIX . STATUS_CODE_USER_NOT_EXITS=> '用户不存在',
    ERROR_PREFIX . STATUS_CODE_LOGIN_MUST_REQUIRE=> '用户名不能为空',
    ERROR_PREFIX . STATUS_CODE_USER_ADD_FAILED=> '用户添加失败',
    ERROR_PREFIX . STATUS_CODE_LOGIN_FAILED => '用户名或密码错误',
    ERROR_PREFIX . STATUS_CODE_MOBILE_EXITS => '手机号已经被注册',
    ERROR_PREFIX . STATUS_CODE_NONSTANDARD_PASSWORD => '密码不规范',
    ERROR_PREFIX . STATUS_CODE_PASSWORD_MUST_REQUIRE => '密码不能为空',
    ERROR_PREFIX . STATUS_CODE_MOBILE_MUST_REQUIRE => '手机不能为空',
    ERROR_PREFIX . STATUS_CODE_LOGIN_EXITS => '用户名已经存在',
    ERROR_PREFIX . STATUS_CODE_LOGIN_DISABLED => '用户被禁用',
    ERROR_PREFIX . STATUS_CODE_TOO_FREQUENT_OPERATION => '操作太频繁',
    ERROR_PREFIX . STATUS_CODE_TOO_MANY_ATTEMPTS => '用户名或密码错误，若输入错误10次，今日将无法登录',
    ERROR_PREFIX . STATUS_CODE_SEND_MESSAGE_FAILED => '验证码发送失败',
    ERROR_PREFIX . STATUS_CODE_LOGIN_AUTH_FAILED => '登录验证错误',
    ERROR_PREFIX . STATUS_CODE_MOBILE_NO_RIGHT => '手机号格式不正确',

    ERROR_PREFIX . STATUS_CODE_USER_SAVE_FAILED => '用户操作失败',

    #role
    ERROR_PREFIX . STATUS_CODE_ADD_ROLE_FAILED => '添加角色失败',
    ERROR_PREFIX . STATUS_CODE_ROLE_NOT_EXISTS => '角色不存在',
    ERROR_PREFIX . STATUS_CODE_ROLE_NAME_EXISTS => '角色名称已经存在',
    ERROR_PREFIX . STATUS_CODE_ROLE_EDIT_DISABLE => '角色不能编辑',

    #member
    ERROR_PREFIX . STATUS_CODE_MEMBER_FAILED => '用户错误',
    ERROR_PREFIX . STATUS_CODE_TOKEN_EXPIRED => 'TOKEN过期',
    ERROR_PREFIX . STATUS_CODE_TOKEN_WILL_EXPIRED => 'TOKEN即将过期',
    ERROR_PREFIX . STATUS_CODE_TOKEN_INVALID => 'TOKEN无效',
];