<?php
/**
 * 个人业务都在这里
 * User: keepwin100
 * Date: 2019-06-13
 * Time: 15:45
 */

namespace app\api\controller;

use api\controller\Api;
use app\api\logic\MemberLogic;
use core\controller\tool\ApiPagination;

class Member extends Api
{
    use ApiPagination;

    /**
     * @var MemberLogic
     */
    protected $logic;

    public function _initialize()
    {
        $this->logic = MemberLogic::singleton();
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 获取通讯录
     * 支持分段获取
     */
    public function getMembers()
    {
        $this->logic->getMembers($this->paginationParams());
    }


}