<?php 
/**
 * 用户登录类
 */
namespace app\api\controller;

use app\api\logic\PassportLogic;
use app\api\validate\PassportValidate;
use core\controller\Api;
use core\service\ApiService;

class Passport extends Api
{
    protected $validate = PassportValidate::class;

    /**
     * @var PassportLogic
     */
    protected $logic;
    
    protected  $no_auth_action =["login","auth"];

    public function _initialize()
    {
        $this->logic  = PassportLogic::singleton();
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 验证登录信息
     * auth?type=account&password=123456&username=admin
     */
    public function auth()
    {
        $requestParams = $this->request->param();
        $this->validate($this->request->param(), $this->validate);
        $api_service = ApiService::singleton();
        $user = $api_service->authUser($this->request->param("username"),$this->request->param("password"));
        if(!is_null($user)){
            $this->result("",STATUS_INVALID_APPID);
        }
        $token = $api_service->getToken($user);
        $this->result($token);
    }

    /**
     * API登录
     */
    public function login()
    {
        $this->checkRequest();
        $username = $this->request->param("app_username");
        $password = $this->request->param("app_password");
        $result = $this->logic->login($username,$password);
        if(empty($result)){
            $this->result("",STATUS_CODE_LOGIN_FAILED);
        }
        $this->result($result);
    }



    
    
}

